#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elmah
{
    using System;
    using System.Collections.Generic;
    
    #line 2 "..\..\MasterPage.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\MasterPage.cshtml"
    using Elmah;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    internal partial class MasterPage : WebTemplateBase
    {
#line hidden

        #line 6 "..\..\MasterPage.cshtml"

    public string Title { get; set; }
    public object Footnote { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");





WriteLiteral("\r\n");


            
            #line 10 "..\..\MasterPage.cshtml"
  
    var basePageName = Request.ServerVariables["URL"];
    
    var now = DateTime.Now;
    var tz = TimeZone.CurrentTimeZone;
    
    var about = PoweredBy.GetAbout(Context.Cache, (version, fileVersion, product, copyright) => new
    {
        Version   = version != null
                  ? version.ToString()
                  : fileVersion != null 
                  ? fileVersion.ToString() 
                  : "?.?.?.?",
        Product   = Mask.EmptyString(product, "(product)"),
        Copyright = copyright,
    });


            
            #line default
            #line hidden
WriteLiteral("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org" +
"/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xh" +
"tml\">\r\n    <head>\r\n        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Emulat" +
"eIE7\" />\r\n");


            
            #line 31 "..\..\MasterPage.cshtml"
         if (!string.IsNullOrEmpty(Title))
        {

            
            #line default
            #line hidden
WriteLiteral("            <title>");


            
            #line 33 "..\..\MasterPage.cshtml"
              Write(Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n");


            
            #line 34 "..\..\MasterPage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");


            
            #line 35 "..\..\MasterPage.cshtml"
                                                Write(basePageName);

            
            #line default
            #line hidden
WriteLiteral("/stylesheet\" />\r\n    </head>\r\n    <body>\r\n        ");


            
            #line 38 "..\..\MasterPage.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        <p id=\"Footer\">\r\n            <span>Powered by <a href=\"http://elmah.goo" +
"glecode.com/\">");


            
            #line 40 "..\..\MasterPage.cshtml"
                                                               Write(about.Product);

            
            #line default
            #line hidden
WriteLiteral("</a>, \r\n                version ");


            
            #line 41 "..\..\MasterPage.cshtml"
                   Write(about.Version);

            
            #line default
            #line hidden
WriteLiteral(".\r\n                ");


            
            #line 42 "..\..\MasterPage.cshtml"
           Write(about.Copyright);

            
            #line default
            #line hidden
WriteLiteral(" \r\n                Licensed under <a href=\"http://www.apache.org/licenses/LICENSE" +
"-2.0\">Apache License, Version 2.0</a>. \r\n            </span>\r\n            Server" +
" date is ");


            
            #line 45 "..\..\MasterPage.cshtml"
                      Write(now.ToString("D", CultureInfo.InvariantCulture));

            
            #line default
            #line hidden
WriteLiteral(". \r\n            Server time is ");


            
            #line 46 "..\..\MasterPage.cshtml"
                      Write(now.ToString("T", CultureInfo.InvariantCulture));

            
            #line default
            #line hidden
WriteLiteral(". \r\n            All dates and times displayed are in the \r\n            ");


            
            #line 48 "..\..\MasterPage.cshtml"
        Write(tz.IsDaylightSavingTime(now) ? tz.DaylightName : tz.StandardName);

            
            #line default
            #line hidden
WriteLiteral(" zone. \r\n            ");


            
            #line 49 "..\..\MasterPage.cshtml"
       Write(Footnote);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </p>\r\n    </body>\r\n</html>\r\n");


        }
    }
}
#pragma warning restore 1591
